name: "studyum-types-registry"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8080:8080
    env_file:
      - ".env"
    volumes:
      - ./db:/var/lib/postgresql/data
