name: CI CD

on: [ push ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          check-latest: true
          cache-dependency-path: |
            go.sum

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...


  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - name: Deploying service
        uses: appleboy/ssh-action@v1.0.3
        with:
          username: ${{ secrets.AWS_USER }}
          host: ${{ secrets.AWS_HOST }}
          key: ${{ secrets.AWS_KEY }}
          port: 22
          script: cd deploy && ./update.sh backend types_registry