name: CI CD

on: [ push ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          check-latest: true
          cache-dependency-path: |
            go.sum

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - name: Deploy
        uses: fjogeleit/http-request-action@v1.15.4
        with:
          url: ${{ secrets.DEPLOYEER_URL }}
          method: 'POST'
          username: ${{ secrets.DEPLOYEER_USERNAME }}
          password: ${{ secrets.DEPLOYEER_PASSWORD }}
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"project": "studyum", "app": "api-types_registry", "async": true}'
